blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('client/', include('service_client.urls', namespace='client')),
    path('mailing/', include('newsletter.urls', namespace='newsletter')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path

from newsletter.apps import NewsletterConfig
from newsletter.views import MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, \
    MessageDeleteView, MailingLogsListView

app_name = NewsletterConfig.name

urlpatterns = [
    path('list/', MessageListView.as_view(), name='message_list'),
    path('list/detail/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('list/create/', MessageCreateView.as_view(), name='message_create'),
    path('list/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('list/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('report/', MailingLogsListView.as_view(), name='report_list'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, GenerateNewPasswordView, UserVerifyView, \
    ManagerView, UserListView, DisableUserView, DisableMessageView, UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/verify/<int:pk>/', UserVerifyView.as_view(), name='verification'),
    path('profile_edit/', UserUpdateView.as_view(), name='profile_edit'),
    path('profile_delete/<int:pk>/', UserDeleteView.as_view(), name='profile_delete'),
    path('profile/genpassword/', GenerateNewPasswordView.as_view(), name='generate_new_password'),
    path('manager/', ManagerView.as_view(), name='manager_profile'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('disable_user/<int:pk>/', DisableUserView.as_view(), name='user_disable'),
    path('disable_message/<int:pk>/', DisableMessageView.as_view(), name='message_disable'),
]

newsletter/models.py
from django.conf import settings
from django.db import models

from service_client.models import Client, NULLABLE


class MailingSettings(models.Model):
    """
    Model for managing mailing settings.

    Attributes:
        send_time (DateTimeField): Date and time for sending the mailing.
        frequency (CharField): Frequency of the mailing (choices: Daily, Weekly, Monthly).
        status (CharField): Status of the mailing (choices: Created, Started, Completed).
    """
    send_time = models.DateTimeField(verbose_name='время рассылки')

    frequency_choices = [
        ('Daily', 'Раз в день'),
        ('Weekly', 'Раз в неделю'),
        ('Monthly', 'Раз в месяц'),
    ]
    frequency = models.CharField(max_length=30, choices=frequency_choices, verbose_name='периодичность')

    status_choices = [
        ('Created', 'Создана'),
        ('Started', 'Запущена'),
        ('Completed', 'Завершена'),
    ]
    status = models.CharField(max_length=30, choices=status_choices, verbose_name='статус рассылки')

    def __str__(self):
        """
        String representation of the object.
        """
        return f'{self.send_time} - {self.frequency}'

    class Meta:
        """
        Meta_class settings for the MailingSettings model.
        """
        verbose_name = 'Настройка'
        verbose_name_plural = 'Настройки'


class Message(models.Model):
    """
    Model for managing messages and their content.

    Attributes:
        client (ManyToManyField): Clients associated with the message.
        mailing_settings (ForeignKey): Mailing settings associated with the message.
        title (CharField): Title of the message.
        body (TextField): Body/content of the message.
        owner (ForeignKey): Owner of the message (linked to settings.AUTH_USER_MODEL).
        is_active (BooleanField): Flag indicating if the message is active or not.
    """
    client = models.ManyToManyField(Client, verbose_name='клиент')
    mailing_settings = models.ForeignKey(MailingSettings, on_delete=models.SET_NULL, null=True,
                                         verbose_name='настройки')

    title = models.CharField(max_length=255, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело письма')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец')
    is_active = models.BooleanField(default=True, verbose_name='признак активности')

    def __str__(self):
        """
        String representation of the object.
        """
        return self.title

    class Meta:
        """
        Meta_class settings for the Message model.
        """
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class MailingLogs(models.Model):
    """
    Model for managing mailing logs.

    Attributes:
        message (ForeignKey): Message associated with the log.
        datetime_attempt (DateTimeField): Date and time of the mailing attempt.
        status (CharField): Status of the mailing attempt.
        server_response (TextField): Server response for the mailing attempt.
    """
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, null=True, verbose_name='рассылка')
    datetime_attempt = models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')
    status = models.CharField(max_length=30, verbose_name='статус попытки')
    server_response = models.TextField(**NULLABLE, verbose_name='ответ почтового сервера')

    def __str__(self):
        """
        String representation of the object.
        """
        return f'{self.status} в {self.datetime_attempt}'

    class Meta:
        """
        Meta_class settings for the MailingLogs model.
        """
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

newsletter/forms.py
from django import forms

from newsletter.models import Message
from newsletter.validators import validate_even


class MessageForm(forms.ModelForm):
    """
    Form for creating or updating a message.

    Attributes:
        title (CharField): Title of the message.
        body (CharField): Body of the message.
    """
    title = forms.CharField(validators=[validate_even],
                            label='Название рассылки',
                            widget=forms.TextInput(
                                attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Впишите название',
                                }
                            ))

    body = forms.CharField(validators=[validate_even],
                           label='Содержимое рассылки',
                           widget=forms.Textarea(
                               attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Напишите содержимое рассылки',
                               }
                           ))

    class Meta:
        """
        Meta_class configuration for the MessageForm.
        """
        model = Message
        fields = ('client', 'title', 'body', 'mailing_settings',)
        widgets = {
            'client': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'mailing_settings': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'client': 'Выберите клиентов(Ctrl+C для выбора нескольких)',
            'mailing_settings': 'Выберите настройки для рассылки',
        }

newsletter/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from newsletter.forms import MessageForm
from newsletter.models import Message, MailingLogs


class MessageListView(LoginRequiredMixin, ListView):
    """
    View for displaying the list of messages.

    Attributes:
        model (Model): The model associated with the view.
        ordering (tuple): The default ordering for the queryset.
        extra_context (dict): Extra context data to be included in the view.
    """
    model = Message
    ordering = ('title',)
    extra_context = {
        'title': 'Список рассылок'
    }


class MessageDetailView(LoginRequiredMixin, DetailView):
    """
    View for detailed view of a message.

    Attributes:
        model (Model): The model associated with the view.
        extra_context (dict): Extra context data to be included in the view.
    """
    model = Message
    extra_context = {
        'title': 'Просмотр рассылки'
    }


class MessageCreateView(LoginRequiredMixin, CreateView):
    """
    View for creating a message.

    Attributes:
        model (Model): The model associated with the view.
        form_class (Form): The form class used for the view.
        success_url (str): The URL to redirect to after successful form submission.
        extra_context (dict): Extra context data to be included in the view.
    """
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('newsletter:message_list')

    extra_context = {
        'title': 'Создание рассылки'
    }

    def form_valid(self, form):
        """
        Assigns the current user as the owner of the message.
        """
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    View for updating a message.

    Attributes:
        model (Model): The model associated with the view.
        form_class (Form): The form class used for the view.
        extra_context (dict): Extra context data to be included in the view.
    """
    model = Message
    form_class = MessageForm

    extra_context = {
        'title': 'Редактирование рассылки'
    }

    def get_success_url(self):
        """
        Redirects to the detailed view of the message upon success.
        """
        return reverse('newsletter:message_detail', args=[self.kwargs.get('pk')])

    def test_func(self):
        """
        Checks whether the user has the rights of the message owner or is a superuser.
        """
        return self.request.user == self.get_object().owner or self.request.user.is_superuser


class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    View for deleting a message.

    Attributes:
        model (Model): The model associated with the view.
        success_url (str): The URL to redirect to after successful deletion.
        extra_context (dict): Extra context data to be included in the view.
    """
    model = Message
    success_url = reverse_lazy('newsletter:message_list')

    extra_context = {
        'title': 'Удаление рассылки'
    }

    def test_func(self):
        """
        Checks whether the user has the rights of the message owner or is a superuser.
        """
        return self.request.user == self.get_object().owner or self.request.user.is_superuser


class MailingLogsListView(LoginRequiredMixin, ListView):
    """
    View for viewing mailing logs.

    Attributes:
        model (Model): The model associated with the view.
        extra_context (dict): Extra context data to be included in the view.
    """
    model = MailingLogs
    extra_context = {
        'title': 'Отчет рассылок'
    }

    def get_queryset(self):
        """
        Checks if the user is a superuser or has the right to view all mailings (staff),
        then displays all mailings, otherwise filters by owner and displays only their logs.
        """
        order_by = self.request.GET.get('order_by', '-datetime_attempt')

        if self.request.user.is_superuser or self.request.user.is_staff:
            return MailingLogs.objects.all().order_by(order_by)
        else:
            return MailingLogs.objects.filter(message__owner=self.request.user).order_by(order_by)

newsletter/templates/newsletter/mailinglogs_list.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="mb-3">
        <a href="?order_by=datetime_attempt" class="btn btn-secondary">Сначала старые</a>
        <a href="?order_by=-datetime_attempt" class="btn btn-secondary">Сначала новые</a>
    </div>

    <table class="table table-hover">
        <caption class="caption-top">Отчет проведенных рассылок</caption>
        <thead class="table-secondary">
        <tr>
            <th scope="col">№</th>
            <th scope="col">Рассылка</th>
            <th scope="col">Дата и время попытки</th>
            <th scope="col">Статус попытки</th>
            <th scope="col">Ответ сервера</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <th scope="row">{{ object.pk }}</th>
                <td>
                    {% if object.message %}
                        <a href="{% url 'newsletter:message_detail' object.message.pk %}"
                           class="custom-link">{{ object.message }}</a>
                    {% else %}
                        <strong style="color:darkred">РАССЫЛКА УДАЛЕНА</strong>
                    {% endif %}
                </td>
                <td>{{ object.datetime_attempt }}</td>
                <td style="color: {% if object.status == 'Sending error' %}red{% elif object.status == 'Successfully sent' %}green{% else %}black{% endif %}">
                    {{ object.status }}
                </td>
                <td>{{ object.server_response }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

newsletter/templates/newsletter/message_confirm_delete.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Вы действительно хотите удалить
                                рассылку {{ object.title }}?</p>
                            <button type="submit" class="btn btn-danger"
                                    title="При нажатии на кнопку, действие отменить будет невозможно">Подтвердить
                            </button>
                            <a href="{% url 'newsletter:message_detail' object.pk %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
{% endblock %}

newsletter/templates/newsletter/message_detail.html
{% extends 'home/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">

            {% if object.owner == user or user.is_superuser or user.is_staff %}
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                {{ object.title|title }}
                            </h3>
                        </div>
                        <div class="card-body">
                            <p>
                                <strong>Содержимое рассылки:</strong><br/>
                                {{ object.body }}
                            </p>
                            <p>
                                <strong>Рассылается для:</strong>
                                {% for client_object in object.client.all %}<br/>
                                    {{ client_object }}
                                {% endfor %}
                            </p>
                            <p>
                                <strong>Настройки рассылки:</strong><br/>
                                {{ object.mailing_settings }}
                            </p>
                            <p>
                                <strong>Владелец рассылки:</strong><br/>
                                {{ object.owner }}
                            </p>
                            <p>
                                <strong>Признак активности:</strong><br/>
                                {% if object.is_active %}
                                    <span class="active-status active">рассылка активна &#9989;</span>
                                {% else %}
                                    <span class="active-status inactive">рассылка не активна &#10060;, напишите в поддержку </span>
                                {% endif %}
                            </p>
                        </div>

                        <div class="card bg-light">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    {% if object.owner == user or user.is_superuser %}
                                        <a href="{% url 'newsletter:message_update' object.pk %}" type="button"
                                           class="btn btn-outline-secondary">Редактировать</a>
                                        <a href="{% url 'newsletter:message_delete' object.pk %}" type="button"
                                           class="btn btn-outline-danger">Удалить</a>
                                    {% endif %}
                                    {% if user.is_staff %}
                                        {% if object.is_active %}
                                            <a href="{% url 'users:message_disable' object.pk %}" type="button"
                                               class="btn btn-outline-danger">Отключить рассылку</a>
                                        {% else %}
                                            <a href="{% url 'users:message_disable' object.pk %}" type="button"
                                               class="btn btn-outline-success">Включить рассылку</a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            {% else %}
                <h3>У вас нет доступа и прав для просмотра этой страницы, вернитесь на предыдущую страницу</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

newsletter/templates/newsletter/message_form.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="col-lg-5 col-md-6 col-sm-12 mx-auto">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                {% if object %}
                    <h5 class="my-0 font-weight-normal">Отредактируйте форму &#128221; с данными рассылки</h5>
                {% else %}
                    <h5 class="my-0 font-weight-normal">Заполните форму &#128221; для создания рассылки</h5>
                {% endif %}
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if object %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-dark">Обновить данные рассылки
                        </button>
                    {% else %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-dark">Добавить рассылку</button>
                    {% endif %}
                </form>

            </div>
        </div>
    </div>
{% endblock %}

newsletter/templates/newsletter/message_list.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="row text-center mb-2">
        {% if user.is_superuser or user.is_staff %}
            <h1>Все рассылки от сервиса Mailing Wave &#128232;</h1>
        {% else %}
            <h1>Ваши рассылки от сервиса Mailing Wave &#128232;</h1>
        {% endif %}
    </div>

    <div class="row text-center">

        {% for object in object_list %}
            {% if object.owner == user or user.is_superuser or user.is_staff %}
                <div class="col-sm-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h5 class="my-0 font-weight-normal">{{ object.title|title }}</h5>
                        </div>
                        <div class="card-body">
                            <a href="{% url 'newsletter:message_detail' object.pk %}" type="button"
                               class="btn btn-lg btn-block btn-outline-primary">Посмотреть подробно</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

        <div class="col-sm-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h5 class="my-0 font-weight-normal">Место для вашей рассылки</h5>
                </div>
                <div class="card-body">
                    <a href="{% url 'newsletter:message_create' %}" type="button"
                       class="btn btn-lg btn-block btn-outline-primary">Создать рассылку</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}