blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('client/', include('service_client.urls', namespace='client')),
    path('mailing/', include('newsletter.urls', namespace='newsletter')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from service_client.apps import ServiceClientConfig
from home.views import HomeView


app_name = ServiceClientConfig.name

urlpatterns = [
    path('', (HomeView.as_view()), name='home'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, GenerateNewPasswordView, UserVerifyView, \
    ManagerView, UserListView, DisableUserView, DisableMessageView, UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/verify/<int:pk>/', UserVerifyView.as_view(), name='verification'),
    path('profile_edit/', UserUpdateView.as_view(), name='profile_edit'),
    path('profile_delete/<int:pk>/', UserDeleteView.as_view(), name='profile_delete'),
    path('profile/genpassword/', GenerateNewPasswordView.as_view(), name='generate_new_password'),
    path('manager/', ManagerView.as_view(), name='manager_profile'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('disable_user/<int:pk>/', DisableUserView.as_view(), name='user_disable'),
    path('disable_message/<int:pk>/', DisableMessageView.as_view(), name='message_disable'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.views.generic import TemplateView
from random import sample
from blog.models import Blog
from home.services import get_cached_clients
from newsletter.models import Message


class HomeView(TemplateView):
    """
    View for the home page.

    Attributes:
        template_name (str): The name of the template used for rendering the view.
        extra_context (dict): Additional context data for the view.
    """
    template_name = 'home/home.html'
    extra_context = {
        'title': 'Mailing Wave'
    }

    def get_context_data(self, **kwargs):
        """
        Get additional context data.

        Returns:
            dict: Context data for the view.
        """
        context_data = super().get_context_data(**kwargs)
        context_data['all_messages'] = Message.objects.all()
        context_data['active_messages'] = Message.objects.filter(is_active=True)
        context_data['all_clients'] = get_cached_clients()
        context_data['articles'] = sample(list(Blog.objects.all()), 3)
        return context_data

home/templates/home/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link rel="icon" href="{% static 'images/icon_mailing.ico' %}" type="image/x-icon">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom_styles.css' %}">

</head>
<body>
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="message {% if message.tags %} {{ message.tags }}{% endif %}">
                {{ message }}
                <span class="close-btn">&times;</span>
            </div>
        {% endfor %}
    </div>
{% endif %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <a href="{% url 'home:home' %}" class="my-0 mr-md-auto font-weight-normal text-decoration-none text-dark h5">Mailing
        Wave &#128235;</a>
    <nav class="ms-5">
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog_list' %}">Наш ТехноБлог</a>
        {% endif %}
    </nav>
    <div class="ms-auto">
        {% if user.is_authenticated %}
            {% if user.avatar %}
                <img src="{{ user.avatar.url }}" alt="" width="40" height="40" class="rounded-circle">
            {% endif %}
            {% if user.is_staff or user.is_superuser %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:manager_profile' %}">Личный кабинет</a>
            {% else %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile_edit' %}">Личный кабинет</a>
            {% endif %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </div>
</div>
<div class="container">

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-6 col-md">
                Mailing management by Pavel Akulich
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                Связаться с поддержкой
                <small class="d-block mb-3 text-muted"><a class="text-muted" href="#">Напишите нам</a></small>
            </div>
        </div>
    </footer>
</div>
<script src="{% static 'js/js_custom.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

home/templates/home/home.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="row text-center">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">&#128204; {{ title }} &#128204;</h1>
        </div>
        <ul class="custom-list">
            <li style="display: inline-block">
                <input type="checkbox" checked="">
                <div>С</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>Е</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>Р</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>В</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>И</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox" checked="">
                <div>С</div>
            </li>
            <p></p>
            <li style="display: inline-block">
                <input type="checkbox" checked="">
                <div>У</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>П</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>Р</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>А</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>В</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>Л</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>Е</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>Н</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>И</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox" checked="">
                <div>Я</div>
            </li>
            <p></p>
            <li style="display: inline-block">
                <input type="checkbox" checked="">
                <div>Р</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>А</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>С</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>С</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>Ы</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>Л</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>К</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>А</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox">
                <div>М</div>
            </li>
            <li style="display: inline-block">
                <input type="checkbox" checked="">
                <div>И</div>
            </li>
        </ul>
    </div>

    <div class="styled-text">
        <span>Наш сервис рассылает столько рассылок:</span>
        <span class="highlight">{{ all_messages | length }}</span>
    </div>

    <div class="styled-text">
        <span>В данный момент активных рассылок:</span>
        <span class="highlight">{{ active_messages | length }}</span>
    </div>

    <div class="styled-text">
        <span>Мы рассылаем наши рассылки для стольких клиентов:</span>
        <span class="highlight">{{ all_clients | length }}</span>
    </div>

    <div class="mb-4"></div>
    <div class="styled-text-article">
        <span class="highlight">Статьи из нашего блога</span>
    </div>

    <div class="d-flex flex-wrap">

        {% for article in articles %}
            <div class="card m-2" style="width: 26rem;">
                {% if article.preview %}
                    <img src="/media/{{ article.preview }}" class="card-img-top" alt="" height="150">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <p class="card-text">{{ article.content|truncatechars:20 }}</p>
                    <a href="{% url 'blog:blog_detail' article.pk %}" class="btn btn-primary">Читать полностью</a><br/>
                    {% if content_manager %}<br/>
                        <a href="{% url 'blog:blog_update' object.pk %}" type="button" class="btn btn-secondary">Редактировать</a>
                        <a href="{% url 'blog:blog_delete' object.pk %}" type="button"
                           class="btn btn-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}