blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('client/', include('service_client.urls', namespace='client')),
    path('mailing/', include('newsletter.urls', namespace='newsletter')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service_client/urls.py
from django.urls import path

from service_client.apps import ServiceClientConfig
from service_client.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, \
    ClientDeleteView

app_name = ServiceClientConfig.name

urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_view'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/edit/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
]

service_client/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """
    Model representing a client of the service.

    Attributes:
        first_name (CharField): The first name of the client.
        last_name (CharField): The last name of the client.
        patronymic (CharField): The patronymic of the client.
        email (EmailField): The email address of the client.
        comment (TextField): Additional comment about the client.
    """
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    patronymic = models.CharField(**NULLABLE, max_length=100, verbose_name='отчество')
    email = models.EmailField(unique=True, max_length=255, verbose_name='почта клиента')
    comment = models.TextField(**NULLABLE, verbose_name='комментарий')

    def __str__(self):
        """
        String representation of the client object.
        """
        return f'Клиент {self.first_name} с почтой {self.email}'

    class Meta:
        """
        Meta_class configuration for the Client model.
        """
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

service_client/forms.py
from django import forms

from service_client.models import Client


class ClientForm(forms.ModelForm):
    """
    Form for creating or updating a client.

    Attributes:
        model (Model): The model associated with the form.
        fields (tuple): The fields to be included in the form.
        widgets (dict): Custom widgets for the form fields.
        labels (dict): Custom labels for the form fields.
    """

    class Meta:
        """
        Meta_class configuration for the ClientForm.
        """
        model = Client
        fields = ('first_name', 'last_name', 'patronymic', 'email', 'comment')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Впишите имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Впишите фамилию'}),
            'patronymic': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Впишите отчество'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Впишите email'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Оставьте комментарий'}),
        }

        labels = {
            'patronymic': 'Отчество(если таковое имеется)',
            'comment': 'Комментарий(опционально)',
        }

service_client/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from service_client.forms import ClientForm
from service_client.models import Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    """
    View for creating a client.

    Attributes:
        model (Model): The model associated with the view.
        form_class (Form): The form class used for the view.
        success_url (str): The URL to redirect to after successful creation.
        extra_context (dict): Extra context data to be included in the view.
    """
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('client:client_list')

    extra_context = {
        'title': 'Создание клиента'
    }


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    View for updating a client.

    Attributes:
        model (Model): The model associated with the view.
        form_class (Form): The form class used for the view.
        extra_context (dict): Extra context data to be included in the view.
    """
    model = Client
    form_class = ClientForm

    extra_context = {
        'title': 'Редактирование клиента'
    }

    def get_success_url(self):
        """
        Redirects to the detailed view of the client upon success.
        """
        return reverse('client:client_view', args=[self.kwargs.get('pk')])

    def test_func(self):
        """
        Checks whether the user has manager rights or is a superuser.
        """
        return self.request.user.groups.filter(name='manager').exists() or self.request.user.is_superuser


class ClientListView(LoginRequiredMixin, ListView):
    """
    View for listing all clients.

    Attributes:
        model (Model): The model associated with the view.
        ordering (tuple): The default ordering for the queryset.
        extra_context (dict): Extra context data to be included in the view.
    """
    model = Client
    ordering = ('last_name',)
    extra_context = {
        'title': 'Клиенты сервиса'
    }


class ClientDetailView(LoginRequiredMixin, DetailView):
    """
    View for detailed view of a client.

    Attributes:
        model (Model): The model associated with the view.
        extra_context (dict): Extra context data to be included in the view.
    """
    model = Client
    extra_context = {
        'title': 'Просмотр клиента'
    }


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    View for deleting a client.

    Attributes:
        model (Model): The model associated with the view.
        success_url (str): The URL to redirect to after successful deletion.
        extra_context (dict): Extra context data to be included in the view.
    """
    model = Client
    success_url = reverse_lazy('client:client_list')

    extra_context = {
        'title': 'Удаление клиента'
    }

    def test_func(self):
        """
        Checks whether the user has manager rights or is a superuser.
        """
        return self.request.user.groups.filter(name='manager').exists() or self.request.user.is_superuser

service_client/templates/service_client/client_confirm_delete.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Вы действительно хотите удалить
                                клиента {{ object.first_name }} {{ object.last_name }}?</p>
                            <button type="submit" class="btn btn-danger"
                                    title="При нажатии на кнопку, действие отменить будет невозможно">Подтвердить
                            </button>
                            <a href="{% url 'client:client_view' object.pk %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
{% endblock %}

service_client/templates/service_client/client_detail.html
{% extends 'home/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">


            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {{ object.first_name|title }} {{ object.last_name|title }}
                            {% if object.patronymic %}
                                {{ object.patronymic|title }}
                            {% else %}
                                <small>(Отчество не указано)</small>
                            {% endif %}
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            {% if object.comment %}
                                <strong>Комментарий клиента:</strong><br/>
                                {{ object.comment }}
                            {% else %}
                                Клиент не оставил комментарий
                            {% endif %}
                        </p>
                    </div>
                    <div class="card-footer mb-1">
                        <strong>Email:</strong> {{ object.email }}
                    </div>
                    {% if user.is_staff or user.is_superuser %}
                        <div class="card bg-light">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'client:client_update' object.pk %}" type="button"
                                       class="btn btn-outline-secondary">Редактировать</a>
                                    <a href="{% url 'client:client_delete' object.pk %}" type="button"
                                       class="btn btn-outline-danger">Удалить</a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

service_client/templates/service_client/client_form.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="col-lg-5 col-md-6 col-sm-12 mx-auto">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                {% if object %}
                    <h5 class="my-0 font-weight-normal">Отредактируйте форму &#128221; с данными клиента</h5>
                {% else %}
                    <h5 class="my-0 font-weight-normal">Заполните форму &#128221; для создания клиента</h5>
                {% endif %}
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {#                    <div class="mb-3">#}
                    {#                        <label for="{{ form.first_name.id_for_label }}">Имя</label><br/>#}
                    {#                        {{ form.first_name }}#}
                    {#                    </div>#}
                    {#                    <div class="mb-3">#}
                    {#                        <label for="{{ form.last_name.id_for_label }}">Фамилия</label><br/>#}
                    {#                        {{ form.last_name }}#}
                    {#                    </div>#}
                    {#                    <div class="mb-3">#}
                    {#                        <label for="{{ form.patronymic.id_for_label }}">Отчество#}
                    {#                            <small>(опционально)</small></label><br/>#}
                    {#                        {{ form.patronymic }}#}
                    {#                    </div>#}
                    {#                    <div class="mb-3">#}
                    {#                        <label for="{{ form.email.id_for_label }}">Email для рассылки</label><br/>#}
                    {#                        {{ form.email }}#}
                    {#                    </div>#}
                    {#                    <div class="mb-3">#}
                    {#                        <label for="{{ form.comment.id_for_label }}">Комментарий#}
                    {#                            <small>(опционально)</small></label><br/>#}
                    {#                        {{ form.comment }}#}
                    {#                    </div>#}
                    {% if object %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-dark">Обновить данные клиента
                        </button>
                    {% else %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-dark">Добавить клиента</button>
                    {% endif %}
                </form>

            </div>
        </div>
    </div>
{% endblock %}

service_client/templates/service_client/client_list.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="row text-center">
        <h1>Список клиентов сервиса Mailing Wave &#128232;</h1>
    </div>

    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-sm-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h5 class="my-0 font-weight-normal">{{ object.first_name|title }} {{ object.last_name|title }}</h5>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li><h6>Email клиента:</h6>{{ object.email }}</li>
                        </ul>
                        <a href="{% url 'client:client_view' object.pk %}" type="button"
                           class="btn btn-lg btn-block btn-outline-primary">Посмотреть подробнее</a>
                    </div>
                </div>
            </div>
        {% endfor %}

        <div class="col-sm-3 mt-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h5 class="my-0 font-weight-normal">Создать клиента рассылки</h5>
                </div>
                <div class="card-body">
                    <a href="{% url 'client:client_create' %}" type="button"
                       class="btn btn-lg btn-outline-primary">Создать клиента</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}