blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('client/', include('service_client.urls', namespace='client')),
    path('mailing/', include('newsletter.urls', namespace='newsletter')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path

from newsletter.apps import NewsletterConfig
from newsletter.views import MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, \
    MessageDeleteView, MailingLogsListView

app_name = NewsletterConfig.name

urlpatterns = [
    path('list/', MessageListView.as_view(), name='message_list'),
    path('list/detail/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('list/create/', MessageCreateView.as_view(), name='message_create'),
    path('list/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('list/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('report/', MailingLogsListView.as_view(), name='report_list'),
]

service_client/urls.py
from django.urls import path

from service_client.apps import ServiceClientConfig
from service_client.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, \
    ClientDeleteView

app_name = ServiceClientConfig.name

urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_view'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/edit/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, GenerateNewPasswordView, UserVerifyView, \
    ManagerView, UserListView, DisableUserView, DisableMessageView, UserDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/verify/<int:pk>/', UserVerifyView.as_view(), name='verification'),
    path('profile_edit/', UserUpdateView.as_view(), name='profile_edit'),
    path('profile_delete/<int:pk>/', UserDeleteView.as_view(), name='profile_delete'),
    path('profile/genpassword/', GenerateNewPasswordView.as_view(), name='generate_new_password'),
    path('manager/', ManagerView.as_view(), name='manager_profile'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('disable_user/<int:pk>/', DisableUserView.as_view(), name='user_disable'),
    path('disable_message/<int:pk>/', DisableMessageView.as_view(), name='message_disable'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from service_client.models import NULLABLE


class User(AbstractUser):
    """
    Custom user model representing a user of the system.

    Attributes:
        email (EmailField): The email address of the user.
        avatar (ImageField): The avatar image of the user.
        phone (CharField): The phone number of the user.
        country (CharField): The country of the user.
        verify_code (CharField): The verification code of the user.
    """
    username = None

    email = models.EmailField(unique=True, verbose_name='email')

    avatar = models.ImageField(upload_to='users_avatar/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=40, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    verify_code = models.CharField(default=0, verbose_name='код верификации')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class UserRegisterForm(UserCreationForm):
    """
    Form for registering a new user.

    Attributes:
        password1 (CharField): The first password input field.
        password2 (CharField): The second password input field for confirmation.
        model (Model): The model associated with the form.
        fields (tuple): The fields to be included in the form.
        widgets (dict): Custom widgets for the form fields.
    """
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Впишите пароль'}),
        label='Пароль')
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Повторите ваш пароль'}),
        label='Повторите пароль')

    class Meta:
        """
        Meta_class configuration for the UserRegisterForm.
        """
        model = User
        fields = ('email', 'password1', 'password2',)

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Впишите email'}),
        }


class UserForm(UserChangeForm):
    """
    Form for updating user information.

    Attributes:
        model (Model): The model associated with the form.
        fields (tuple): The fields to be included in the form.
        widgets (dict): Custom widgets for the form fields.
    """

    class Meta:
        """
        Meta_class configuration for the UserForm.
        """
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'avatar', 'phone', 'country',)

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Впишите email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Впишите имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Впишите фамилию'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Впишите номер телефона'}),
            'country': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Впишите страну'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class VerificationForm(forms.Form):
    """
    Form for verification code input.

    Attributes:
        verify_code (CharField): The field for entering the verification code.
    """

    verify_code = forms.CharField(max_length=12, label='Введите код верификации')

users/views.py
import random
import string

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, View, ListView, DeleteView

from newsletter.models import Message
from users.forms import UserRegisterForm, UserForm, VerificationForm
from users.models import User


class LoginView(BaseLoginView):
    """
    View for user login.
    """
    template_name = 'users/login.html'
    extra_context = {
        'title': 'Log in to account'
    }

    def form_valid(self, form):
        """
        Creates a success message about successful login.
        """
        response = super().form_valid(form)
        messages.success(self.request, 'Вы успешно авторизовались')
        return response


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    """
    View for user registration.
    """
    model = User
    extra_context = {
        'title': 'Registration'
    }
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        """
        Handler called when form is successfully validated.
        Creates a new user, sets their activation status to False, generates a unique verification code,
        saves the user, and sends an email with the verification code to the user's email address.
        """
        user = form.save(commit=False)
        user.is_active = False
        generate_code = ''.join([str(random.randint(0, 9)) for _ in range(12)])
        user.verify_code = generate_code
        user.save()

        # Sending an email with the activation code
        send_mail(
            subject='Код верификации',
            message=f'Пожалуйста, для вашей верификации и активации аккаунта введите код: {generate_code}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return redirect(reverse('users:verification', kwargs={'pk': user.pk}))


class UserVerifyView(View):
    """
    View for user verification during registration.
    """
    template_name = 'users/verification.html'
    extra_context = {
        'title': 'Verification'
    }

    def get(self, request, *args, **kwargs):
        form = VerificationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        """
        Compares the entered code with the one sent to the user's email for verification.
        """
        form = VerificationForm(request.POST)
        if form.is_valid():
            entered_code = form.cleaned_data['verify_code']
            user_pk = kwargs.get('pk')
            user = get_object_or_404(User, pk=user_pk)

            if entered_code == user.verify_code:
                user.is_active = True
                user.save()
                messages.success(request, 'Аккаунт успешно активирован!')
                return redirect(reverse('users:login'))
            else:
                messages.error(request, 'Неверный код верификации. Попробуйте снова.')

        return render(request, self.template_name, {'form': form})


class UserListView(UserPassesTestMixin, ListView):
    """
    View for displaying the list of users.
    """
    model = User
    extra_context = {
        'title': 'Our Users'
    }

    def test_func(self):
        """
        Checks whether the user has manager rights or is a superuser.
        """
        return self.request.user.groups.filter(name='manager').exists() or self.request.user.is_superuser


class GenerateNewPasswordView(View):
    """
    View for generating a new password.
    """

    def generate_random_password(self, length=12):
        """
        Generates a new random password.
        """
        characters = string.ascii_letters + string.digits
        return ''.join(random.choice(characters) for _ in range(length))

    def get(self, request, *args, **kwargs):
        new_password = self.generate_random_password()
        # Send email with the new password
        send_mail(
            subject='Password reset',
            message=f'Your new password: {new_password}\n'
                    f'Login with your new password',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[request.user.email]
        )
        request.user.set_password(new_password)
        request.user.save()
        return redirect(reverse('users:login'))


class UserUpdateView(UpdateView):
    """
    View for editing user data.
    """
    model = User
    extra_context = {
        'title': 'Edit profile'
    }
    success_url = reverse_lazy('users:profile_edit')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


class UserDeleteView(DeleteView):
    """
    View for deleting a user.
    """
    model = User
    success_url = reverse_lazy('home:home')
    extra_context = {
        'title': 'Delete account',
    }


class ManagerView(UserPassesTestMixin, View):
    """
    View for the manager interface.
    """
    template_name = 'users/manager.html'

    def get(self, request, *args, **kwargs):
        context = {
            'title': 'Manager account',
        }
        return render(request, self.template_name, context)

    def test_func(self):
        """
         Checks if the user has manager rights or is a superuser.
         """
        return self.request.user.groups.filter(name='manager').exists() or self.request.user.is_superuser


class DisableUserView(UserPassesTestMixin, View):
    """
    View for deactivating (blocking) or activating a user.
    """

    def get(self, request, pk):
        user = User.objects.get(pk=pk)

        if user.is_active:
            user.is_active = False
        elif not user.is_active:
            user.is_active = True

        user.save()
        return redirect('users:users_list')

    def test_func(self):
        """
        Checks if the user has manager rights or is a superuser.
        """
        return self.request.user.groups.filter(name='manager').exists() or self.request.user.is_superuser


class DisableMessageView(UserPassesTestMixin, View):
    """
    View for disabling/enabling a message.
    """

    def get(self, request, pk):
        message = Message.objects.get(pk=pk)

        if message.is_active:
            message.is_active = False
        elif not message.is_active:
            message.is_active = True

        message.save()
        return redirect('newsletter:message_detail', pk=pk)

    def test_func(self):
        """
        Checks if the user has manager rights or is a superuser.
        """
        return self.request.user.groups.filter(name='manager').exists() or self.request.user.is_superuser

users/templates/users/login.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h5>Войдите в аккаунт или <a href="{% url 'users:register' %}" class="text-dark">зарегистрируйтесь</a></h5>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <div>
                                {{ form.as_p }}
                            </div>

                            <button type="submit" class="btn btn-primary">Войти</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/manager.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row justify-content-center">
            <div class="col-12 text-center mb-4">
                <h1>Добро пожаловать в инструментарий менеджера &#128736;</h1>
            </div>
            <div class="card col-5 mb-2 mx-auto">
                <h6>Отредактировать личные данные</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile_edit' %}">К профилю</a>
            </div>
            <div class="card col-5 mb-2 mx-auto">
                <h6>Посмотреть всех пользователей сервиса</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:users_list' %}">К пользователям</a>
            </div>
            <div class="card col-5 mb-2 mx-auto">
                <h6>Посмотреть все рассылки</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'newsletter:message_list' %}">К рассылкам</a>
            </div>
            <div class="card col-5 mb-2 mx-auto">
                <h6>Отчет(логи) рассылок</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'newsletter:report_list' %}">К логам</a>
            </div>
            <div class="card col-5 mb-2 mx-auto">
                <h6>Посмотреть всех клиентов сервиса</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'client:client_list' %}">К клиентам</a>
            </div>
            <div class="card col-5 mb-2 mx-auto">
                <h6>Перейти в административную панель</h6>
                <a class="p-2 btn btn-outline-primary" href="{% url 'admin:index' %}">К админке</a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'home/base.html' %}
{% block content %}
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h5>Регистрация</h5>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <div>
                                {{ form.as_p }}
                                <small>&#10071; Ваш пароль должен содержать как минимум 8 символов</small><br/>
                                <small>&#10071; Пароль не должен быть слишком простым и распространенным</small><br/>
                                <small>&#10071; Пароль не может состоять только из цифр</small>
                            </div>

                            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Вы действительно хотите удалить
                                пользователя {{ object.email }}?</p>
                            <button type="submit" class="btn btn-danger"
                                    title="При нажатии на кнопку, действие отменить будет невозможно">Подтвердить
                            </button>
                            <a href="{% url 'users:profile_edit' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
{% endblock %}

users/templates/users/user_form.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-12 col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <h5>Профиль {{ object.first_name }}</h5>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <div>
                                {{ form.as_p }}
                            </div>
                            <button type="submit" class="btn btn-primary">Обновить данные</button>
                        </div>

                        <div class="card-footer">
                            <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать
                                новый
                                пароль</a>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'users:profile_delete' object.pk %}" class="btn btn-danger">Удалить аккаунт</a>
                        </div>

                    </div>
                </div>

                {% if not user.is_staff %}
                    <div class="col-12 col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h5>Доступный функционал</h5>
                            </div>
                            <div class="card-body">
                                <a class="p-2 btn btn-outline-primary" href="{% url 'client:client_list' %}">Клиенты
                                    сервиса</a>
                                <a class="p-2 btn btn-outline-primary"
                                   href="{% url 'newsletter:message_list' %}">Мои рассылки</a>
                                <a class="p-2 btn btn-outline-primary" href="{% url 'newsletter:report_list' %}">Отчет
                                    по
                                    рассылкам</a>
                            </div>
                            <div class="card-footer">
                                Управляйте рассылками и просматривайте клиентов, смотрите отчеты
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="row text-center">
        <h1>Список пользователей сервиса Mailing Wave &#128232;</h1>
    </div>

    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-sm-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h6 class="my-0 font-weight-normal">Email пользователя: {{ object.email }}</h6>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li><h6>Данные пользователя:</h6></li>
                            Имя: {{ object.first_name }}<br/>
                            Фамилия: {{ object.last_name }}<br/>
                            Признак активности:
                            {% if object.is_active %}
                                Активен
                            {% else %}
                                Отключен
                            {% endif %}
                            id пользователя: {{ object.pk }}
                        </ul>
                        {% if object.is_active %}
                            <a href="{% url 'users:user_disable' object.pk %}" type="button"
                               class="btn btn-lg btn-block btn-outline-primary">Отключить юзера</a>
                        {% else %}
                            <a href="{% url 'users:user_disable' object.pk %}" type="button"
                               class="btn btn-lg btn-block btn-outline-primary">Активировать юзера</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

users/templates/users/verification.html
{% extends 'home/base.html' %}

{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Активация аккаунта</h1>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Верификация аккаунта</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            <p>Мы отправили письмо на вашу почту, чтобы подтвердить регистрацию аккаунта</p>
                            {% csrf_token %}
                            <div class="mb-3">
                                <input type="text" name="verify_code" class="form-control" id="verify_code"
                                       placeholder="Введите код из письма" required>
                            </div>
                            <input type="submit" class="btn btn-success">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}